### ISSUE TITLE
Feature request - separate activity section on homepage

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/ohmg#10]
Currently, https://oldinsurancemaps.net/loc/volumes/ lists all available or loaded volumes.  A logged-in user should be able to see volumes they've contributed to (defined by loading a volume or preparing/georeferencing/trimming a sheet in said volume). Optionally, they can permanently hide volumes they contributed to from this section.

This would replace a current workflow where I favorite the first sheet of each volume I contribute to and then unfavorite when I'm done with the volume.

**Comment by mradamcox** [comment]
@BNAndras Let me know what you think... any suggestions welcome!
