### ISSUE TITLE
Can't enlarge thumbnail images of Georeferenced maps

### ISSUE THREAD

**Issue by rchampine** [mradamcox/ohmg#144]
**Describe the problem**
This is a very minor bug. Unlike the map images under the Unprepared and Prepared sections, it is not possible to click and enlarge map images under the Georeferenced section. On hover over one of these images, the cursor changes to a magnifying glass with the tool tip "inspect layer in standalone map", but it's not clickable.

**Expected behavior**
It should be possible to click to enlarge the map images under Georeferenced.

**Environment info:**
 - Device: MacBook Pro
 - Operating System: macOS Ventura 13.4
 - Browser: Arc and Chrome

**Comment by mradamcox** [comment]
Thanks for marking this, it's something @jeffreyameyer pointed out to me a long time ago and has slipped through the cracks. Putting an openlayers map into a modal, like what you see in the resource page, would be a nice improvement, and could be replicated for the content in the Prepared section as well.

**Comment by mradamcox** [comment]
Fixed now with OpenLayers in modal approach.
![image](https://github.com/mradamcox/ohmg/assets/10427268/53b2e056-a1e5-473d-9c27-2f0df52fc691)
