### ISSUE TITLE
[Request] Order sheets in MultiMask list by number and type

### ISSUE THREAD

**Issue by rchampine** [mradamcox/ohmg#157]
To make it easier to find sheets in the MultiMask process, sheets should be ordered by number. It could also be beneficial to separate the sheets into two sections in the list — Masked vs. not yet Masked.

**Comment by mradamcox** [comment]
@rchampine Addressed this over the weekend. Let me know what you think.

**Comment by rchampine** [comment]
This is great! Thanks for tackling.
