### ISSUE TITLE
[Bug] Page Not Found for Prepared Sheets 

### ISSUE THREAD

**Issue by rchampine** [mradamcox/ohmg#162]
For these two prepared sheets, all links to lead to Page Not Found
https://oldinsurancemaps.net/resource/11518/
https://oldinsurancemaps.net/resource/11517

Prepared section: https://oldinsurancemaps.net/loc/sanborn00169_008/#prepared
<img width="446" alt="image" src="https://github.com/mradamcox/ohmg/assets/136510277/3e87e4a3-c6ef-4d01-9fe8-eb9c7260cc1c">

**Comment by mradamcox** [comment]
I believe this was a side effect of #148 , when I repaired the lookup (with the repair button) references to these sheets were removed from the prepared section.

**Comment by rchampine** [comment]
Excellent — thanks!
