### ISSUE TITLE
"Undo this determination" button not working

### ISSUE THREAD

**Issue by rchampine** [mradamcox/ohmg#167]
On this specific map: https://oldinsurancemaps.net/resource/7582 the "Undo this determination" button does not complete its task when clicked. The button is working for me on other maps.

https://github.com/mradamcox/ohmg/assets/136510277/dff161dd-66cd-49c7-b109-363bc747bf87

**Comment by mradamcox** [comment]
I'm guessing it's failing because it doesn't expect there to be two preparation sessions, which shouldn't be allowed to happen but seems to have here (need better checks for that). I'll can sort this page out this weekend, not a problem.

**Comment by mradamcox** [comment]
Looks to be sorted out now.
