### ISSUE TITLE
Load volumes not functioning

### ISSUE THREAD

**Issue by rchampine** [mradamcox/ohmg#179]
Looks like loading volumes is not currently working — at least three all stay at "0/xxx" after clicking load.
https://oldinsurancemaps.net/map/sanborn07905_033
https://oldinsurancemaps.net/map/sanborn08348_024
https://oldinsurancemaps.net/map/sanborn08492_014

**Comment by mradamcox** [comment]
Sorry. I assume it's connected to the #178 . Should be working tomorrow.

**Comment by rchampine** [comment]
Excellent — thanks!
