### ISSUE TITLE
[Bug] Volume map button arrangement on mobile device

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/ohmg#65]
**Describe the problem**
Volume map buttons run off the edge of the viewer.

**Expected behavior**
Buttons should resize or flow into another row of buttons.

**Environment info:**
 - Device: iPhone 8
 - Operating System: iOS 15.4
 - Browser: Safari

**Additional context**
![F85747A2-EFC6-4FA2-A422-A27318C23B0F](https://user-images.githubusercontent.com/20251272/158296337-04e938a0-7635-4137-82d0-a5430241e939.png)

**Comment by mradamcox** [comment]
May be nice to set overflow-x to scroll for these buttons... I feel like modular side-scrolling is pretty common on mobile now.

**Comment by mradamcox** [comment]
These wrap now.
