### ISSUE TITLE
[Bug] Full-screen button while georeferencing doesn't work in Safari

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/ohmg#84]
**Describe the problem**
When georeferencing, the full-screen button doesn't activate when clicked in Safari. Full-screen mode does work if I click the full-screen button on the volume map viewer. This bug is specific to Safari because both buttons work as expected in Chrome.
 
**Environment info:**
 - Device: Mac mini M1
 - Operating System: macOS Monterey 12.0
 - Browser: Safari 15.3

**Comment by BNAndras** [comment]
Not a significant bug in itself since we've previously established the website doesn't go fully full-screen for Safari anyways.

**Comment by mradamcox** [comment]
Fullscreen now handled in a better way.
